name: sparks_dating_app
description: SP dating app with Firebase Auth, CRUD, chat, and chatbot.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0

  provider: ^6.1.2
  intl: ^0.19.0

  google_fonts: ^6.2.1
  # Profile photos & chat photos
  firebase_storage: ^12.3.0
  image_picker: ^1.1.2
  cloud_functions: ^5.2.0
  google_mlkit_image_labeling: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sp_logo.png